[project]
name = "pipdep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "beautifulsoup4[lxml]>=4.13.4",
    "packaging>=25.0",
    "pyyaml>=6.0.2",
]
